### ISSUE TITLE
Use latest into-docker version

### ISSUE THREAD

**Issue by r0man** [into-docker/build-action#2]
Hello Yannick,

I played a bit around with into-docker and quite like it. I'm
using a locally checked out version of into-docker because I had
a segfault with the native image published on Github.

I made my first builder for shadow-cljs and got it working
locally. Now I'm trying to use the Github build action, but
noticed a permission problem while building. I think I'm running
into this [1]. Any chance the build action could be updated to a
version that includes this fix. I believe the Github action uses
a version that does not include this commit.

I have another question regarding into-docker. Are you also using
it to run tests and do linting? This isn't really mentioned in
the whitepaper. At the moment I test and lint inside the builder,
but was wondering what the recommended aproach is?

Thanks, Roman.

[1] https://github.com/into-docker/into-docker/commit/bb4814176d97b1d84fd6953d3c9f24cde4f9d67b

**Comment by xsc** [comment]
Hey @r0man!
I seem to not have been a "Watcher" of this project for some reason, so I never got a notification about your question. :/ I'll create a prerelease that can be referenced in the build action to address your problems, probably already tonight.

> Are you also using it to run tests and do linting? 

I did not have that on the radar, but it could be something that can be added neatly, e.g. by providing the possibility to have one or more `lint`/`test` scripts in the builder image, and CLI flags to enable/disable those steps.

I'm not sure it's super useful for local usage, but on CI this can be a nice addition. There are some things to consider, though, e.g. how to handle lint/test artifacts (e.g. coverage reports).

**Comment by xsc** [comment]
@r0man Version [`1.1.0-RC1`](https://github.com/into-docker/into-docker/releases/tag/v1.1.0-RC1) has been released. You can use the `version` parameter to use it:

```yaml
- uses: into-docker/build-action@v1
  with:
    image: target-image:latest
    builder: intodocker/clojure
    version: 1.1.0-RC1
    # ...
```

**Comment by r0man** [comment]
Nice, thank you!

**Comment by r0man** [comment]
I just tried it out, and it works. Thanks again!
